In [1]:
# Ruta de la carpeta con los archivos CSV en el portátil 
carpeta_origen = 'C:/Users/TITAN OSCURO/Desktop/Datos bicing'

In [ ]:
# Ruta de la carpeta con los archivos CSV en la torre
carpeta_origen = "C:/Users/isana/Desktop/Datos bicing"

In [2]:
import pandas as pd
import os

# Leer el archivo CSV y guardarlo en un dataframe
ruta_archivo = os.path.join(carpeta_origen, 'Informacio_Estacions_Bicing_2025.csv')
Info_bicing_csv = pd.read_csv(ruta_archivo)

# Visualizar el contenido del dataframe
print('Dataframe cargado exitosamente: Info_bicing_csv')

Dataframe cargado exitosamente: Info_bicing_csv

In [3]:
# Creación de sample 10.000 casos solo 2024
import os
import pandas as pd

# Definir la carpeta origen donde están los archivos CSV
carpeta_origen = "C:/Users/TITAN OSCURO/Desktop/Datos bicing"  # Cambia esto por la ruta correcta

# Crear una lista para almacenar los dataframes del año 2024
dataframes_2024 = []

# Iterar sobre los archivos en la carpeta origen
for archivo in os.listdir(carpeta_origen):
    # Verificar si el archivo corresponde al año 2024 y es un CSV
    if archivo.startswith("2024") and archivo.endswith(".csv"):
        # Leer el archivo CSV y añadirlo a la lista de dataframes
        ruta_archivo = os.path.join(carpeta_origen, archivo)
        df = pd.read_csv(ruta_archivo)
        dataframes_2024.append(df)

# Combinar todos los dataframes del año 2024 en uno solo
if dataframes_2024:  # Verificar que la lista no esté vacía
    dataframe_2024 = pd.concat(dataframes_2024, ignore_index=True)

    # Crear un sample de hasta 10,000 filas
    dataframe_sample_2024 = dataframe_2024.sample(n=min(10000, len(dataframe_2024)), random_state=42)

    print("Se ha creado un sample de hasta 10,000 filas del año 2024, llamado 'dataframe_sample_2024'.")
else:
    print("No se encontraron archivos para el año 2024.")

C:\Users\TITAN OSCURO\AppData\Local\Temp\ipykernel_22984\934571680.py:17: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_archivo)
C:\Users\TITAN OSCURO\AppData\Local\Temp\ipykernel_22984\934571680.py:17: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_archivo)
C:\Users\TITAN OSCURO\AppData\Local\Temp\ipykernel_22984\934571680.py:17: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_archivo)
C:\Users\TITAN OSCURO\AppData\Local\Temp\ipykernel_22984\934571680.py:17: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_archivo)
C:\Users\TITAN OSCURO\AppData\Local\Temp\ipykernel_22984\934571680.py:17: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(ruta_archivo)

Se ha creado un sample de hasta 10,000 filas del año 2024, llamado 'dataframe_sample_2024'.

In [4]:
# eliminacoión de columnas sin información
dataframe_sample_2024.drop(columns=['traffic','V1'], inplace=True)

In [5]:
# eliminación de NA por si se han colado con la selección de datos random:
dataframe_sample_2024.dropna(inplace=True)

# transformación de la variable tiempo:
dataframe_sample_2024['last_reported']=pd.to_datetime(dataframe_sample_2024['last_reported'], unit='s')
dataframe_sample_2024['last_updated']=pd.to_datetime(dataframe_sample_2024['last_updated'], unit='s')

In [6]:
dataframe_sample_2024.head(5)

,station_id,num_bikes_available,num_bikes_available_types.mechanical,num_bikes_available_types.ebike,num_docks_available,last_reported,is_charging_station,status,is_installed,is_renting,is_returning,last_updated,ttl
16987735,334.0,3.0,0.0,3.0,23.0,2024-04-27 03:42:07,True,IN_SERVICE,1.0,1.0,1.0,2024-04-27 03:45:03,0.0
17673025,196.0,8.0,1.0,7.0,17.0,2024-05-01 19:42:34,True,IN_SERVICE,1.0,1.0,1.0,2024-05-01 19:45:03,0.0
13759447,264.0,19.0,18.0,1.0,14.0,2024-04-05 01:41:07,True,IN_SERVICE,1.0,1.0,1.0,2024-04-05 01:45:02,0.0
14877624,163.0,5.0,4.0,1.0,21.0,2024-04-12 17:52:20,True,IN_SERVICE,1.0,1.0,1.0,2024-04-12 17:55:05,1.0
16711243,230.0,11.0,7.0,4.0,14.0,2024-04-25 06:29:41,True,IN_SERVICE,1.0,1.0,1.0,2024-04-25 06:30:05,0.0

In [8]:
# Eliminación de variables que no sirven
Info_bicing_csv.drop(columns='rental_uris', inplace=True)
Info_bicing_csv.drop(columns='is_valet_station', inplace=True)

In [9]:
# Encontrar los índices de las filas que cumplen con la condición
indices_a_eliminar = Info_bicing_csv[Info_bicing_csv['address'] == 'Copa América Barcelona 2024'].index

# Eliminar las filas específicas
Info_bicing_csv.drop(indices_a_eliminar, inplace=True)

# Datos restantes NA tras la eliminación:
Info_bicing_csv[Info_bicing_csv.isnull().any(axis=1)]

,station_id,name,physical_configuration,lat,lon,altitude,address,cross_street,post_code,capacity,is_charging_station,short_name,nearby_distance,_ride_code_support
9,10,"C/ 60, NÚMERO 25",ELECTRICBIKESTATION,41.346775,2.143623,NaN,"C/ 60, NÚMERO 25",03-Sants-Montjuïc/12-la Marina del Prat Vermell,8040.0,43,True,10,1000.0,True
10,11,"PG. MARITIM, 11 (DAVANT PL. BRUGADA)",ELECTRICBIKESTATION,41.382398,2.194294,NaN,"PG. MARITIM, 11 (DAVANT PL. BRUGADA)",01-CiutatVella/03-la Barceloneta,8003.0,35,True,11,1000.0,True
53,59,"C/ AGUSTÍ DURAN I SANPERE, 1",ELECTRICBIKESTATION,41.381382,2.168078,NaN,"C/ AGUSTÍ DURAN I SANPERE, 1",01-CiutatVella/01-el Raval,8001.0,22,True,59,1000.0,True
259,271,"VIA BARCINO, 69",ELECTRICBIKESTATION,41.451987,2.193523,NaN,"VIA BARCINO, 69",09-SantAndreu/57-la Trinitat Vella,8033.0,15,True,271,1000.0,True
338,350,"C/ LONDRES, 63",ELECTRICBIKESTATION,41.391756,2.148291,NaN,"C/ LONDRES, 63",02-Eixample/08-l'Antiga Esquerra de l'Eixample,8036.0,31,True,350,1000.0,True
369,381,"C/ AGUSTÍ DURAN I SANPERE, 10",ELECTRICBIKESTATION,41.381636,2.167729,NaN,"C/ AGUSTÍ DURAN I SANPERE, 10",01-CiutatVella/01-el Raval,8001.0,40,True,381,1000.0,True
507,527,"PG. OLIMPIC, 8",ELECTRICBIKESTATION,41.361973,2.154322,NaN,"PG. OLIMPIC, 8",03-Sants-Montjuïc/11-el Poble-sec,8038.0,36,True,527,1000.0,True
515,544,"C/ MONTFAR, 1",ELECTRICBIKESTATION,41.370490,2.148729,NaN,"C/ MONTFAR, 1",03-Sants-Montjuïc/14-la Font de la Guatlla,8004.0,24,True,520,1000.0,True

In [15]:
Info_bicing_csv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 514 entries, 0 to 515
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   station_id              514 non-null    int64
 1   name                    514 non-null    object
 2   physical_configuration  514 non-null    object
 3   lat                     514 non-null    float64
 4   lon                     514 non-null    float64
 5   altitude                506 non-null    float64
 6   address                 514 non-null    object
 7   cross_street            514 non-null    object
 8   post_code               514 non-null    float64
 9   capacity                514 non-null    int64
 10  is_charging_station     514 non-null    bool
 11  short_name              514 non-null    int64
 12  nearby_distance         514 non-null    float64
 13  _ride_code_support      514 non-null    bool
dtypes: bool(2), float64(5), int64(3), object(4)
memory usage: 53.2+ KB

In [13]:
Info_bicing_csv.isna().sum()

station_id                0
name                      0
physical_configuration    0
lat                       0
lon                       0
altitude                  8
address                   0
cross_street              0
post_code                 0
capacity                  0
is_charging_station       0
short_name                0
nearby_distance           0
_ride_code_support        0
dtype: int64

In [10]:
Info_bicing_csv.head(5)

,station_id,name,physical_configuration,lat,lon,altitude,address,cross_street,post_code,capacity,is_charging_station,short_name,nearby_distance,_ride_code_support
0,1,"GRAN VIA CORTS CATALANES, 760",ELECTRICBIKESTATION,41.397978,2.180107,16.0,"GRAN VIA CORTS CATALANES, 760",02-Eixample/05-el Fort Pienc,8013.0,46,True,1,1000.0,True
1,2,"C/ ROGER DE FLOR, 126",ELECTRICBIKESTATION,41.395488,2.177198,17.0,"C/ ROGER DE FLOR, 126",02-Eixample/05-el Fort Pienc,8013.0,29,True,2,1000.0,True
2,3,"C/ NÀPOLS, 82",ELECTRICBIKESTATION,41.394156,2.181331,11.0,"C/ NÀPOLS, 82",02-Eixample/05-el Fort Pienc,8013.0,27,True,3,1000.0,True
3,4,"C/ RIBES, 13",ELECTRICBIKESTATION,41.393317,2.181248,8.0,"C/ RIBES, 13",02-Eixample/05-el Fort Pienc,8013.0,21,True,4,1000.0,True
4,5,"PG. LLUIS COMPANYS, 11 (ARC TRIOMF)",ELECTRICBIKESTATION,41.391103,2.180176,7.0,"PG. LLUIS COMPANYS, 11 (ARC TRIOMF)","01-CiutatVella/04-Sant Pere, Santa Caterina i ...",8018.0,39,True,5,1000.0,True